package de.femtopedia.ldpc;

import java.nio.file.Paths;
import java.util.SplittableRandom;
import java.util.stream.Collectors;
import org.bouncycastle.pqc.math.linearalgebra.GF2Matrix;
import org.bouncycastle.pqc.math.linearalgebra.GF2Vector;

import static de.femtopedia.ldpc.MatrixUtils.addNoise;
import static de.femtopedia.ldpc.MatrixUtils.toVec;

/**
 * Provides a simple example as test case.
 */
public final class Test {

    /**
     * Don't initialize me.
     */
    private Test() {
        throw new UnsupportedOperationException();
    }

    /**
     * Starting point of the program.
     *
     * @param args The starting arguments.
     */
    public static void main(String[] args) {
        // This matrix comes from
        // http://www.inference.org.uk/mackay/codes/10000.10000.3.631/
        GF2Matrix h = LDPCGenerator.readAList(Paths.get("demonstration", "A"));

        if (h == null) {
            System.out.println("The parsed alist file is not valid.");
            return;
        }

        // For some reason, the matrix has to be transposed beforehand.
        h = (GF2Matrix) h.computeTranspose();

        LDPC ldpc = new LDPC(h, 0.1, 20, "pic");
        GF2Vector msg = toVec(PICTURE);
        GF2Vector encoded = ldpc.encode(msg);

        GF2Vector recvMsg = addNoise(new GF2Vector(encoded),
                new SplittableRandom().ints(1500, 0, encoded.getLength())
                        .boxed().collect(Collectors.toSet()));

        ldpc.decode(recvMsg);
    }

    /**
     * The 100x100 picture to encode and decode.
     * Source: http://www.inference.org.uk/mackay/codes/gifs/
     */
    private static final boolean[] PICTURE = new boolean[]{false, false, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true,
            true, false, false, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true,
            true, true, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true,
            true, true, true, true, true, true, false, false, false, false,
            false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            false, false, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, false, false, true, true, true, false, false, false, false,
            false, true, true, true, false, false, false, false, false, true,
            true, false, false, false, false, false, true, true, true, true,
            true, true, true, true, true, true, true, false, true, true, true,
            true, false, true, true, false, false, false, false, false, false,
            true, true, true, true, true, false, true, true, true, true, false,
            true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, false, true, true, true, false, false, true, false,
            false, true, true, true, false, false, false, false, false, true,
            true, false, false, false, false, false, false, true, true, true,
            false, true, true, true, false, true, true, false, false, true,
            true, true, false, false, true, false, false, true, false, false,
            false, false, true, true, true, false, false, true, true, true,
            true, false, false, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, false, true, true, true, false, false, true, true,
            false, true, true, true, false, true, true, true, true, true,
            true, false, false, true, true, true, false, false, true, false,
            false, true, true, true, false, false, true, false, false, false,
            true, true, false, false, true, false, false, true, true, true,
            true, false, true, true, true, false, false, false, true, true,
            true, false, false, false, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, false, true, true, true, false, false, true, true,
            false, true, true, true, false, false, true, true, true, true,
            true, false, false, true, true, true, true, false, true, false,
            false, true, true, true, true, false, true, false, true, false,
            true, true, false, false, true, false, false, true, true, true,
            true, false, false, true, false, false, true, false, true, true,
            true, false, false, false, false, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, false, true, true, true, true, false, false, false,
            false, true, true, true, false, false, false, false, true, true,
            true, false, false, true, true, true, true, false, true, false,
            true, true, true, true, true, false, true, false, true, false,
            false, true, true, false, true, true, false, true, true, true,
            true, false, false, true, false, false, true, false, false, true,
            true, false, false, true, false, false, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, false, true, true, true, true, false, false, false,
            false, true, true, true, false, false, true, true, true, true,
            true, false, false, true, true, true, false, false, true, false,
            true, true, true, true, true, false, true, false, true, true,
            false, false, true, false, true, true, false, true, true, true,
            true, false, false, true, false, true, true, false, false, true,
            true, false, false, true, true, false, false,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, false, true, true, true, true, false, true, true,
            false, false, true, true, false, false, true, true, true, true,
            true, true, false, true, true, true, false, false, true, false,
            true, true, true, true, false, false, true, false, true, true,
            true, false, false, false, true, true, false, true, true, true,
            true, false, true, true, false, false, false, false, false, false,
            true, true, false, true, true, true, false,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, false, true, true, true, true, false, true, true,
            true, false, false, true, false, false, true, true, true, true,
            true, true, false, true, true, false, false, true, true, false,
            false, true, true, true, false, false, true, false, false, true,
            true, false, false, false, true, true, false, false, true, true,
            false, false, true, false, false, false, false, true, false,
            false, true, true, false, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, false, true, true, true, true, false, true, true,
            true, true, false, true, true, false, false, false, false, false,
            true, true, false, false, false, false, true, true, true, true,
            false, false, true, false, false, true, true, false, true, true,
            true, true, false, false, true, true, false, false, false, false,
            false, true, true, false, false, true, true, true, true, false,
            true, true, false, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, false, true, true, true, true, false, true, true,
            true, true, false, true, true, false, false, false, true, true,
            true, true, false, false, true, true, true, true, true, true,
            false, false, false, false, true, true, true, true, true, true,
            true, true, true, false, true, true, true, false, false, true,
            true, true, true, false, true, true, true, true, true, false,
            false, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, false, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, false, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, false, false, true, true, true,
            false, false, false, true, true, true, false, false, false, false,
            false, true, true, true, false, false, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true,
            true, true, true, true, true, false, false, false, true, true,
            false, false, false, false, true, false, false, true, false,
            false, false, false, true, true, false, false, false, true, true,
            true, true, false, true, true, true, true, false, false, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true,
            true, true, true, false, false, false, true, false, false, false,
            false, true, true, true, false, false, true, true, true, false,
            false, true, true, true, true, false, true, true, true, true,
            true, false, false, true, true, true, true, false, false, false,
            false, false, false, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, false, false, false,
            true, true, false, false, true, true, true, true, true, false,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, false,
            true, true, true, true, true, true, true, true, true, true,
            false, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, false,
            false, false, false, false, false,
            true, true, false, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, false, false, false,
            false, true, true, true, true, true, true, true, true, true, true,
            false, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            false, true, true, true, true, true, true, true, true, false,
            false, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, false,
            false, true, true, true, true, true,
            true, true, false, false, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, false, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            false, true, true, true, true, true, false, false, false, true,
            true, true, false, false, true, true, true, true, true, true,
            true, false, false, true, true, true, true, true, false, false,
            false, false, true, true, true, true, true, false, false, false,
            true, true, true, true, true, true, true, true, true, true, true,
            false, true, true, true, true, true, true,
            true, true, true, true, false, false, false, false, false, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, false, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            false, true, true, true, true, false, false, true, true, false,
            true, true, false, false, true, true, true, true, true, true,
            false, false, false, true, true, true, true, false, false, false,
            true, true, true, true, true, true, false, false, false, false,
            false, true, true, true, true, true, true, true, true, true,
            false, false, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, false, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            false, true, true, true, false, false, true, true, true, true,
            true, true, false, false, true, true, true, true, true, true,
            false, false, false, false, true, true, true, false, false, true,
            true, true, true, true, true, true, false, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            false, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, false, false, true,
            true, true, true, true, true, true, true, true, true, true, true,
            false, true, true, true, false, false, true, true, true, true,
            true, true, false, false, true, true, true, true, true, true,
            false, false, true, false, false, true, true, true, false, false,
            false, false, false, true, true, true, false, false, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            false, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, false, false, true,
            true, true, true, true, true, true, true, true, true, true, true,
            false, true, true, true, false, true, true, true, true, false,
            false, true, true, false, true, true, true, true, true, true,
            false, true, true, false, false, true, true, true, true, false,
            false, false, false, false, true, true, false, false, false,
            false, false, true, true, true, true, true, true, true, true,
            true, true, false, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, true, true,
            true, true, true, true, true, true, true, true, true, true,
            false, true, true, true, false, true, true, false, false, false,
            false, true, true, false, true, true, true, true, true, true,
            false, false, false, false, false, false, true, true, true, true,
            true, true, true, false, false, true, true, true, true, true,
            false, false, true, true, true, true, true, true, true, true,
            true, false, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, true, true,
            true, true, true, true, true, true, true, true, true, true,
            false, true, true, true, false, true, true, true, true, true,
            false, true, true, false, true, true, true, true, true, false,
            false, false, true, true, true, false, true, true, true, true,
            true, true, true, false, false, true, true, true, true, true,
            true, false, false, true, true, true, true, true, true, true,
            true, false, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, true, true,
            true, true, true, true, true, true, true, true, true, true,
            false, true, true, true, false, false, false, true, true, true,
            false, true, true, false, false, true, true, true, true, false,
            false, true, true, true, true, false, false, true, true, false,
            true, true, true, false, false, true, true, true, true, true,
            true, false, true, true, true, true, true, true, true, true, true,
            false, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, true, true,
            true, true, true, true, true, true, true, true, true, true,
            false, false, true, true, true, false, false, false, false, false,
            false, true, true, false, false, false, false, false, true,
            false, false, true, true, true, true, true, false, true, true,
            false, false, false, false, false, true, true, false, false,
            false, false, false, false, true, true, false, true, true, true,
            true, true, true, false, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, false,
            true, true, true, true, true, true, true, true, true, true, true,
            false, false, true, true, true, true, true, false, false, true,
            true, true, true, true, true, true, true, true, true, false,
            false, true, true, true, true, true, true, true, true, true,
            false, false, true, true, true, true, false, false, false, false,
            false, true, true, false, false, true, true, true, true, true,
            false, false, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, false,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, false,
            true, true, true, true, true, true, true, true, true, true, true,
            true, false, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, false, true, true, true,
            true, true, true, true,
            true, true, true, true, true, true, true, true, false, false,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true,
            true, false, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, false, false, true, true,
            true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, false, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, false, false, true, true, true,
            true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, false, false, false, false, false, false, false,
            false, false, true, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, false, false, false, true, true, true, true,
            true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, false,
            false, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, false, true, true, true, true, true, true, false, false,
            false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, false,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            false, true, true, true, true, true, true, false, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true,
            true, true, true, true, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, false,
            false, false, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            false, true, true, true, true, true, true, false, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true,
            true, true, true, true, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, false, false, false, false, false,
            true, true, true, false, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, false, true, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, false, false, true, true, true, false,
            true, true, true, false, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, false, true, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, false, true, true, true, true, false,
            true, true, true, false, false, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, false, true, true, true, true, true, false, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, false, true, true, true, true, false,
            false, false, false, false, false, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, false, true, true, true, true, true, false, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, false,
            false, true, true, true, true, true, true, true, true, true, true,
            true, true, true, false, false, true, true, true, true, true,
            false, true, true, true, false, false, false, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, false, true, true, true, true, true, false, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, false,
            false, false, false, false, true, true, true, false, false, false,
            false, false, false, false, false, false, true, true, true,
            true, true, false, true, true, true, true, true, false, false,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, false, false, true, true, true, true, false, false,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, false,
            false, true, true, true, false, false, false, false, true, true,
            true, true, true, true, true, false, true, true, true, true, true,
            false, true, true, true, true, true, true, false, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            false, false, true, true, true, true, false, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, false, true,
            false, false, true, true, true, true, true, true, true, true,
            true, true, true, true, true, false, true, true, true, false,
            true, true, true, true, true, true, true, false, false, true,
            true, true, true, true, true, true, true, true, true, true, true,
            false, true, true, true, true, false, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, false,
            false, false, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, false, false, false,
            false, true, true, true, true, true, true, true, true, false,
            true, true, true, true, true, true, true, true, true, true, true,
            false, false, true, true, true, false, false, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, false,
            false, false, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, false, false, true,
            true, true, true, true, true, true, true, true, true, false,
            false, true, true, true, false, false, true, true, true, true,
            true, true, true, true, true, true, false, false, false, false,
            false, false, false, false, false, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, false,
            false, false, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, false, false, true,
            true, true, true, true, true, true, true, true, false, false,
            true, true, false, false, true, true, true, true, true, true,
            true, true, true, true, false, false, false, true, true, true,
            true, true, true, true, false, false, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, false,
            true, false, false, false, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, false, true, true, true,
            true, true, true, true, true, true, false, false, true, false,
            false, false, true, true, true, true, true, true, true, true,
            true, true, true, false, false, false, false, false, false, false,
            false, false, false, false, false, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, false, true,
            true, false, true, true, false, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, false, false, true, true, true,
            true, true, true, true, true, false, false, false, false, false,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, false, true, true, true, true, true, true, true, true,
            true, true, false, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, false,
            true, true, true, true, true, true, true, true, true, false,
            false, true, true, true, false, false, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, false, false, false, false, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, false, false, false, false, false, false, false, true,
            true, true, true, false, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, false,
            true, true, true, true, true, true, true, true, true, true, false,
            false, false, false, false, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            false, false, false, false, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, false, false, false, false, true, true, false, true, true,
            true, true, false, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, false,
            true, true, true, true, true, true, true, true, true, true, false,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, false, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, false,
            false, false, true, true, false, false, false, false, true,
            true, true, true, false, false, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, false,
            true, true, true, true, true, true, true, true, true, true, false,
            false, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, false, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, false,
            false, true, true, true, true, true, false, false, false, false,
            false, false, false, false, false, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, false,
            true, true, true, true, true, true, true, true, true, true, false,
            false, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, false, false, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, false, true,
            true, true, false, false, false, false, true, false, true, true,
            true, false, false, false, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, false,
            true, true, true, true, true, true, true, true, true, true, false,
            false, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, false, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, false,
            true, true, false, false, false, false, false, false, false,
            false, false, false, true, true, false, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, false,
            true, true, true, true, true, true, true, true, true, true, false,
            false, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, false, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, true, true,
            true, false, false, true, true, false, false, false, true, true,
            true, true, true, false, true, true, true, true, true, true,
            true, true, true, false, false, false, false, false, false, false,
            false, false, false, false, false, false,
            true, true, true, true, true, true, true, true, true, true, false,
            false, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, false, false, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, true, true,
            true, false, false, true, true, false, true, true, true, true,
            true, true, true, false, true, true, true, true, true, true, true,
            true, false, true, false, false, true, true, false, false,
            false, false, true, true, false, false,
            true, true, true, true, true, true, true, true, true, true, true,
            false, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, false, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, false, false, true,
            true, true, true, false, true, true, true, true, true, true, true,
            true, true, true, false, true, true, true, true, true, true,
            true, false, true, true, true, true, true, true, true, true, true,
            true, true, true, false, false,
            true, true, true, true, true, true, true, true, true, true, true,
            false, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, false, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, false, true, true, true,
            true, true, false, true, true, true, true, true, true, true,
            true, true, false, false, true, true, true, true, true, true,
            false, false, true, true, true, true, true, true, true, true,
            true, true, true, true, false, false,
            true, true, true, true, true, true, true, true, true, true, false,
            false, false, false, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, false, false, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, false, true, true, true,
            true, true, false, true, false, false, false, false, false,
            false, false, true, false, false, true, true, true, true, true,
            true, false, true, true, true, true, true, true, true, true, true,
            true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true, false,
            false, true, true, false, false, false, false, false, false,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, false, false, false,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, false, false, true, true, true, false, false, true,
            true, true, true, false, false, true, true, true, true, true,
            true, true, true, false, false, true, true, true, true, true,
            true, false, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true, false,
            false, true, true, true, true, true, true, true, false, false,
            false, false, false, false, false, false, false, false, false,
            true, true, true, true, true, true, true, true, false, false,
            false, false, false, true, true, true, true, true, true, true,
            true, true, true, false, false, false, true, true, true, false,
            true, true, true, true, true, false, false, false, false, false,
            false, false, false, false, false, false, true, true, true, true,
            true, true, false, false, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true, false,
            false, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, false, false, false,
            false, false, false, false, false, false, false, false, false,
            true, true, false, true, true, true, true, true, true, true, true,
            true, false, false, true, true, false, true, true, false, true,
            true, true, true, false, false, true, true, true, false, false,
            true, true, true, true, true, true, true, true, true, true, true,
            false, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true, true,
            false, false, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, false, false, false, false, true,
            true, false, true, true, true, true, true, true, true, false,
            false, true, true, true, false, false, false, true, true, true,
            true, true, false, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true, true,
            false, false, false, false, false, false, false, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, false, false, false, false,
            false, false, false, true, false, false, false, false, false,
            false, false, true, true, true, true, true, false, true, true,
            true, true, true, true, false, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, false,
            false, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true, true,
            false, false, true, true, true, true, false, false, false, false,
            false, false, false, true, true, true, true, true, true, true,
            true, true, true, true, true, false, false, false, false, false,
            false, false, false, false, false, true, true, true, false, false,
            false, false, true, true, true, true, false, false, true, true,
            true, true, false, false, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true, true,
            false, true, true, true, true, true, true, true, true, true, true,
            true, false, false, false, false, false, false, false, true,
            true, true, true, true, true, false, true, true, true, true,
            false, false, false, true, true, true, true, true, false, false,
            false, false, false, true, true, true, true, false, true, true,
            true, false, false, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, false, true,
            false, true, true, true, true, true, true, true, true, true,
            false, false, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, false,
            false, false, false, false, true, true, false, true, true, true,
            true, false, false, true, false, true, true, true, true, false,
            false, false, false, false, false, true, true, true, true, false,
            true, false, false, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, false,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, false, true,
            false, true, true, true, true, true, true, true, false, false,
            false, false, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, false, false, false, false, false, false, false,
            false, false, false, true, false, true, true, true, true, true,
            false, false, false, false, false, false, true, true, true, false,
            false, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, false, false, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, false, false, true,
            true, false, true, true, true, true, true, false, false, false,
            false, false, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, false, false, false,
            false, false, true, false, false, true, true, true, true, false,
            false, false, false, false, false, false, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, false, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, false, false, true,
            true, false, true, true, true, true, false, false, false, false,
            false, false, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, false, false, false,
            false, false, false, false, false, false, true, true, true, false,
            false, false, false, false, false, false, true, false, false,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, false, false, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, false, false, true,
            true, false, true, true, true, false, false, false, false, false,
            false, false, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, false, false, false,
            false, false, false, true, true, false, false, true, true, false,
            false, false, false, false, false, false, false, false, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, false, false, true, true, true, true,
            true, true, true, true, false, false, false, false, false, false,
            false, false, false, false, false, false, false, true, true,
            true, false, false, true, true, false, false, false, false, false,
            false, false, true, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, false, false, true,
            true, true, true, false, true, true, false, true, true, false,
            false, false, false, false, false, false, false, false, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, false, true, true, true, true, true, true,
            false, false, false, false, true, true, true, true, true, true,
            false, true, false, false, true, false, true, true,
            true, true, false, true, true, false, false, false, false, false,
            true, false, true, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, false,
            false, true, true, true, true, true, true, true, true, false,
            true, true, true, true, false, false, true, false, false, false,
            false, true, false, false, false, false, false, false, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, false, false, true, true, false, false,
            false, false, true, true, true, false, false, false, false, true,
            false, true, false, false, false, false, true, false, true, true,
            false, true, false, true, true, false, false, false, false, false,
            true, false, true, true, true, true, true, false, false, true,
            true, true, true, true, true, true, true, true, true, true, false,
            true, true, true, true, true, true, true, true, false, true,
            true, true, true, true, false, false, true, false, false, true,
            true, true, false, false, false, false, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, false, true, true, false, false, true, true, false,
            false, false, false, true, true, true, false, true, false, true,
            false, true, true, true, true, false, true, true,
            false, true, false, true, false, false, false, false, false,
            false, true, false, true, true, true, true, true, false, false,
            true, true, true, true, true, true, true, true, true, true, true,
            false, false, true, true, true, true, true, true, true, true,
            false, true, true, true, true, false, false, false, false, true,
            true, true, true, true, false, false, false, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, false, true, true, false, false, false, false, false,
            true, true, false, false, false, true, false, true, false, false,
            false, true, true, true, true, true, false, true, true,
            false, true, false, true, false, false, false, false, false,
            false, true, false, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, false, true, true, true, true, true, true, true, true,
            false, true, true, true, false, false, false, false, false, false,
            true, true, true, true, false, false, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, false, true, true, true, false, false, false, false, false,
            false, false, true, true, true, true, false, true, false, true,
            false, true, true, true, true, false, false, true, true,
            false, true, false, false, false, false, false, false, false,
            false, true, false, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, false, true, true, true, true, true, true, true, true, true,
            false, true, false, false, false, false, false, false, false,
            true, true, true, true, false, false, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, false, true, true, false, false, false, true, true, true,
            false, false, false, false, false, false, false, true, false,
            false, false, true, true, true, true, false, false, false, false,
            false, true, false, false, false, false, false, false, false,
            true, true, false, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, false, true, true, true, true, true, true, true, true, true,
            false, false, false, false, false, false, false, false, false,
            true, true, false, false, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            false, true, true, true, false, false, false, false, false, false,
            true, false, true, false, true, false, true, false, true, false,
            true, true, true, true, true, true, false, false, false,
            false, true, true, false, false, false, false, false, false,
            false, true, false, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, false, false, true, true, true, true, true, true, true,
            true, true, false, false, false, false, false, false, false,
            false, false, false, false, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            false, false, true, true, false, false, false, false, true, true,
            false, false, false, false, false, false, false, true, false,
            true, false, true, true, true, true, true, true, true, true, true,
            false, false, true, false, false, false, false, false, false,
            true, true, false, true, true, true, true, true, false, false,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, false, true, true, true, true, true, true, true, true,
            true, true, true, false, false, false, false, false, false,
            false, false, false, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, false,
            true, true, false, false, false, false, false, false, false,
            false, false, true, false, true, false, true, true, false, false,
            true, true, true, true, true, true, true, true, true, true,
            true, false, true, false, false, false, false, false, false,
            false, true, false, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, false, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, false, false, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, true, true,
            true, false, false, false, false, true, false, true, false,
            true, true, false, true, false, true, false, true, false, true,
            true, true, true, true, true, true, true, true, false,
            true, false, true, false, false, false, false, false, false,
            false, true, false, true, true, true, true, true, false, true,
            true, true, true, true, true, true, true, true, false, false,
            false, false, false, false, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, false, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, false, false, true,
            true, false, false, false, false, false, false, false, false,
            false, true, false, true, false, true, true, false, true, false,
            true, true, true, true, true, true, true, true, true, false,
            true, false, true, false, false, false, false, false, false,
            false, true, false, true, true, true, true, true, true, false,
            false, false, false, false, false, false, false, false, false,
            false, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, false, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, true,
            true, false, false, false, false, false, false, false, true,
            false, true, true, false, true, false, true, false, true, false,
            true, true, true, true, true, true, true, true, true, true, false,
            true, false, false, false, false, false, false, false, false,
            false, true, false, false, true, true, true, true, true, true,
            true, true, true, true, false, false, true, true, true, false,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, false,
            false, true, true, true, false, false, true, true, true, true,
            true, true, true, true, true, true, true, false, true, true, true,
            false, false, false, true, false, true, false, false, false,
            false, false, true, false, true, true, false, true, false, true,
            true, true, true, true, true, true, true, true, false, false,
            true, false, false, false, false, false, false, false, false,
            false, true, false, false, true, true, true, true, true, true,
            true, true, true, true, false, false, true, true, true, false,
            false, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            false, true, true, true, true, false, false, true, true, true,
            true, true, true, true, true, true, false, false, true, true,
            false, false, false, false, false, false, false, false, true,
            false, true, false, true, false, true, false, false, false, false,
            true, true, true, true, true, true, true, true, true, false,
            false,
            true, false, false, true, false, false, false, false, false,
            false, true, false, false, true, true, true, true, true, true,
            true, true, true, true, false, false, true, true, true, true,
            false, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, false, true, true, true, true, false, true, true, true,
            true, true, true, true, true, true, false, true, true, true,
            false, false, false, false, true, true, false, false, false,
            false, false, true, false, false, true, false, true, false, true,
            true, true, true, true, true, true, true, true, true, false, false,
            false, false, false, true, false, true, true, false, false, false,
            true, false, false, true, true, true, true, true, true, true,
            true, true, true, false, false, false, true, true, true, false,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            false, true, true, true, true, false, true, true, true, true,
            true, true, true, false, true, true, true, false, false, false,
            true, false, false, false, false, true, false, true, false, true,
            false, true, true, false, true, false, true, true, true, true,
            true, true, true, true, true, true, false, true,
            true, true, true, true, true, false, false, false, false, false,
            true, false, false, true, true, true, true, true, true, true,
            true, true, true, true, false, false, true, true, true, false,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            false, false, true, true, true, true, false, true, true, true,
            true, true, false, false, true, true, false, false, false, false,
            false, false, true, false, true, false, false, false, true, true,
            false, true, false, true, false, false, true, true, true, true,
            true, true, true, true, true, true, false, true,
            false, false, false, true, true, false, false, false, false,
            false, true, false, false, true, true, true, true, true, true,
            true, true, true, true, true, false, false, true, true, true,
            false, false, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, false, false, true, true, true, true, false,
            true, true, true, true, false, true, true, true, false, false,
            false, true, false, true, false, false, false, false, true, true,
            true, false, false, true, false, true, false, true, true, true,
            true, true, true, true, true, true, true, true, false, true,
            true, true, false, false, true, false, false, false, false, false,
            true, false, false, true, true, true, true, true, true, true,
            true, true, true, true, false, false, true, true, true, true,
            false, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, false, true, true, true, true, true, false,
            true, true, false, true, true, true, false, true, false, true,
            false, false, false, false, true, true, true, true, true, false,
            false, true, false, false, true, false, true, true, true, true,
            true, true, true, true, true, true, true, false, true,
            true, true, false, false, false, false, false, false, false,
            false, false, true, false, true, true, true, true, true, true,
            true, true, true, true, true, false, false, true, true, true,
            true, false, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, false, true, true, true, true, true,
            false, false, false, true, true, true, false, false, false,
            true, false, true, true, false, false, false, false, false, false,
            false, true, true, false, true, false, true, true, true, true,
            true, true, true, true, true, true, true, true, false, true,
            true, true, false, true, false, false, false, false, false, false,
            false, true, false, true, true, true, true, true, true, true,
            true, true, true, true, true, false, true, true, true, true,
            false, false, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, false, false, true, true, true, true,
            false, false, true, true, true, false, true, false, false, false,
            false, false, false, false, true, true, true, true, true, true,
            true, true, false, true, false, true, true, true, true, true,
            true, true, true, true, true, true, true, false, false,
            true, true, false, true, true, false, false, false, false, false,
            false, true, false, true, true, true, true, true, true, true,
            true, true, true, true, true, false, true, true, true, true,
            false, false, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, false, true, true, true, true,
            false, true, true, true, false, false, true, false, false, true,
            true, true, true, false, false, false, false, false, false, false,
            false, false, true, false, false, true, true, true, true, true,
            true, true, true, true, true, true, true, false, false,
            true, true, true, false, true, false, false, false, false, false,
            false, false, false, true, true, true, true, true, true, true,
            true, true, true, true, true, false, false, true, true, true,
            true, false, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, false, false, true, true, false,
            false, true, true, true, false, true, false, false, false, false,
            false, false, false, false, true, true, true, true, true, true,
            true, false, false, false, true, true, true, true, true, true,
            true, true, true, true, true, true, true, false, false,
            true, true, true, false, true, false, false, false, false, false,
            false, true, false, true, true, true, true, true, true, true,
            true, true, true, true, true, false, false, true, true, true,
            true, false, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, false, true, true, true, false,
            true, true, true, false, false, false, false, false, true, true,
            true, true, true, true, true, true, true, true, true, true, true,
            false, false, false, true, true, true, true, true, true, true,
            true, true, true, true, true, true, false, false,
            true, true, true, false, true, false, false, false, false, false,
            false, false, false, true, true, true, true, true, true, true,
            true, true, true, true, true, false, false, true, true, true,
            true, false, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, false, true, true,
            true, true, false, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, false,
            false, false, true, true, true, true, true, true, true, true,
            true, true, true, true, true, false, false};

}
