image: maven:3.6.3-jdk-8

before_script:
  - which java
  - which javac

verify:
  script:
    - mvn compile checkstyle:check -Dcheckstyle.config.location=https://femtopedia.de/checkstyle_new.xml

build:
  script:
    - mvn clean install
  artifacts:
    paths:
      - target/*.jar
    expire_in: never