name: Build using Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build using Maven
        run: mvn clean install
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: LDPC
          path: target/ldpc-*.jar
          if-no-files-found: error