name: Build using Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Run Checkstyle
        run: mvn compile checkstyle:check -Dcheckstyle.config.location=https://femtopedia.de/checkstyle_new.xml
      - name: Build using Maven
        run: mvn clean install
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: LDPC
          path: target/ldpc-*.jar
          if-no-files-found: error
